Lamuni/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf.urls.i18n import i18n_patterns

urlpatterns = i18n_patterns(
    path('admin/', admin.site.urls),
    path("accounts/", include("Users.urls")),
    path("", include("Users.urls")),
    path("", include("Wallet.urls")),
    path("", include("Loans.urls")),
    path("accounts/", include("Users.urls")),
    path("fsp/", include("Loans.urls")),
    path('', include("Lessons.urls")),
    path('accounts/', include('django.contrib.auth.urls')),
    path('i18n/', include('django.conf.urls.i18n')),
    path('ckeditor/', include('ckeditor_uploader.urls')),
    # path('rosetta/', include('rosetta.urls')),
    prefix_default_language=True,
)

Loans/urls.py
from django.urls import path
from .views import create_loan, loan_details, dashboard, loans_list, fsp_profile, \
    loan_beneficiaries, add_record, add_sales_record, fs, fr, user_loan_details, \
    list_loans, apply_loan, users_credentials, grant_loan, deny_loan, generate_income_statement, \
    request_financial_statements, verify_transfer, beneficiary_data

app_name = 'loans'

urlpatterns = [
    path('add/record/', add_record, name='add-record'),
    path('fs/', fs),
    path('fr/<int:pk>/', fr),
    path('add/sales/record/', add_sales_record, name='add-sales-record'),
    path('pdf/', generate_income_statement),
    # path('balance-sheet/', GenerateBalanceSheet.as_view()),
    path('create-loan/', create_loan, name="create_loan"),
    path('loan-details/<int:pk>/', loan_details, name="loan_details"),
    path('user-loan-details/<int:pk>/', user_loan_details, name="user-loan-details"),
    path('dashboard/', dashboard, name="dashboard"),
    path('loans/', loans_list, name='loans_list'),
    path('fsp/profile/', fsp_profile, name='profile'),
    path('loans/<int:pk>/beneficiaries/', loan_beneficiaries, name='beneficiaries'),
    path('loans/<int:loan_pk>/beneficiaries/<int:beneficiary_pk>', beneficiary_data, name='beneficiary_data'),
    path('list-loans', list_loans, name="list_loans"),
    path('apply-loan/<int:id>/', apply_loan, name="apply_loan"),
    path('users-credential/<int:loan_id>/<slug:username>/', users_credentials, name="users_loan_requirements"),
    path('grant-loan/<int:loan_id>/<slug:username>/', grant_loan, name="approve_loan"),
    path('deny-loan/<int:loan_id>/<slug:username>/', deny_loan, name="deny_loan"),
    path('request-financial-statement/', request_financial_statements, name="request-statement"),
    path('transfer/verify', verify_transfer, name="verify_transfer"),
    # path("recommended-loans/", recommended_loans, name="recommended_loans")
]

Users/urls.py
from .views import (chating, index, register,verify_code, send_reset_code, reset_verify,
    reset_password, education,lesson_detail, lesson_done,  user_profile, conversation, financial_statement,
    update_user_profile,  verification)

from django.contrib.auth import views as auth_views
from django.urls import path

app_name = "users"

urlpatterns = [
    path("", index, name="index"),
    path("signup/", register, name="signup"),
    path('logout/', auth_views.LogoutView.as_view(template_name='registration/logout.html')),
    path('verify/<slug:username>/', verify_code, name="verify"),  # ← new
    path('send_reset/', send_reset_code, name="reset_code"),
    path('reset_verify/<slug:username>/', reset_verify, name="reset_verify"),
    path('password_reset/<slug:username>/<int:code>/', reset_password, name="reset_password"),
    path('profile/', user_profile, name="profile"),
    path('profile/update', update_user_profile, name="update_profile"),
    path("bot/", chating, name="bot"),
    path("conversation/", conversation, name="conversation"),
    path("financial-statement/", financial_statement, name="financial-statement"), 
    path('verify/', verification, name="verify")
]

Loans/models.py
from importlib.metadata import requires
from pyexpat import model
from string import digits
from django.utils import timezone
from django.db import models
from django.contrib.auth import get_user_model
from django.urls import reverse
from multiselectfield import MultiSelectField
from datetime import datetime, timedelta

from django.conf import settings
from django.utils.timezone import make_aware
from django.shortcuts import get_object_or_404

from Users.models import Sector

# naive_datetime = datetime.now()
# naive_datetime.tzinfo
#
# settings.TIME_ZONE  # 'UTC'
# aware_datetime = make_aware(naive_datetime)
# aware_datetime.tzinfo  # <UTC>
#
# print(aware_datetime.tzinfo)

# Create your models here.
REQUIREMENTS = (('address', 'address'),
                ('bvn', 'bvn'), ('nin', 'nin'), ('business_certificate', 'business_certificate'),
                ('financial_record', 'financial_record'), ('time_in_business', 'time_in_business'),
                ('number_of_employee', 'number_of_employee'))
BUSINESS_SIZE = (('MICRO', 'MICRO'), ('SMALL', 'SMALL'), ('MEDIUM', 'MEDIUM'))


class FSP(models.Model):
    user = models.ForeignKey(get_user_model(), on_delete=models.DO_NOTHING, related_name='fsp_user')


# class FSP(models.Model):
#     user = models.ForeignKey(get_user_model(), on_delete=models.DO_NOTHING)


class Beneficiaries(models.Model):
    print("beneficairies model")
    user = models.ForeignKey(settings.AUTH_USER_MODEL, on_delete=models.DO_NOTHING, related_name="beneficiary")
    time_applied = models.DateTimeField(auto_now=True)
    time_payed = models.DateTimeField(blank=True, null=True)
    is_payed = models.BooleanField(default=False)
    time_to_pay = models.DateTimeField(blank=True, null=True)  # oficailly the time the loan suppose to be paid
    number_of_employee = models.PositiveIntegerField()
    is_given = models.BooleanField(default=False)
    is_denied = models.BooleanField(default=False)

    def __str__(self) -> str:
        return str(self.user.username)

    @property
    def is_recommended(self, loan_id):
        # TODO: check if the applicants credit score is greater than 50%
        loan = get_object_or_404(Loan, id=loan_id)
        all_beneficiaries = self.objects.filter(user=self.user, is_given=True, is_payed=False)
        if all_beneficiaries.exists():
            return (False, 0)
        if self.user.sector in loan.sectors.all() and self.user.size in loan.size:
            return (True, 10)
        elif self.user.size in loan.size:
            return (True, 7)
        elif self.user.sector in loan.sectors.all():
            return (True, 5)
        # call fake recommend api


class Requirement(models.Model):
    requirement = models.CharField(choices=REQUIREMENTS, max_length=50)

    def __str__(self) -> str:
        return str(self.requirement)


# for choice in REQUIREMENTS:
#     requirements = Requirement.objects.filter(requiremenent=choice[0])
#     if not requirements.exists():
#         Requirement.objects.create(requiremenent=choice[0])


class Loan(models.Model):
    fsp = models.ForeignKey(get_user_model(), on_delete=models.DO_NOTHING, related_name="fsp")
    description = models.TextField()
    date_created = models.DateTimeField(auto_now_add=True)
    program_title = models.CharField(max_length=200)
    size = MultiSelectField(choices=BUSINESS_SIZE, max_choices=3, max_length=100)
    sectors = models.ManyToManyField(Sector)
    amount = models.PositiveIntegerField()
    beneficiaries = models.ManyToManyField(Beneficiaries)
    is_active = models.BooleanField(default=True)
    paying_days = models.PositiveIntegerField()
    grace_period = models.PositiveIntegerField()
    collateral = models.CharField(max_length=200, blank=True, null=True)
    requirements = models.ManyToManyField(Requirement)
    intrest = models.PositiveIntegerField()

    def number_of_approved(self):
        beneficiaries = self.beneficiaries.all()
        count = 0
        for beneficiary in beneficiaries:
            if beneficiary.is_given:
                count += 1
        return count

    def get_sector_data(self):
        pass
        # beneficiaries = self.beneficiaries.all()
        # data = {}
        # for beneficiary in beneficiaries:
        #     sector = beneficiary.user.sector.all()
        #     print("sectors", sector)
        #     it_exist = data.get(sector.name, 0)
        #     if it_exist == 0:
        #         data[sector.name] = 1
        #     else:
        #         data[sector.name] += 1
        # return data

    # number_of_approved = loan.beneficiaries.filter(is_given=True).count()

    def number_of_yet_paid(self):
        beneficiaries = self.beneficiaries.all()
        count = 0
        for beneficiary in beneficiaries:
            if not beneficiary.is_payed:
                count += 1
        return count

    def number_of_paid(self):
        beneficiaries = self.beneficiaries.all()
        count = 0
        for beneficiary in beneficiaries:
            if beneficiary.is_payed:
                count += 1
        return count

    def grant_loan(self, user):
        # TODO: send notif or message to the user that loan granted
        application = self.beneficiaries.filter(user=user)
        print(application[0].is_given)
        if application.exists():
            the_id = application[0].id
            application = get_object_or_404(Beneficiaries, id=the_id)
            application.is_given = True
            application.is_denied = False
            application.time_to_pay = datetime.today() + timedelta(days=self.paying_days)
            application.save()
            return True
        return False

    def deny_loan(self, user):
        # TODO: deny loan tomorow test
        application = self.beneficiaries.filter(user=user)
        if application.exists():
            the_id = application[0].id
            application = get_object_or_404(Beneficiaries, id=the_id)
            # apply is_denied to be true
            application.is_denied = True
            application.is_given = False
            application.save()
            return True
            # TODO: send the user a sorry message that this isnt the right program for him
        return False

    def grant_recommended(self):
        # TODO: this will grant all recommended and deny all unrecommended
        for beneficiary in self.beneficiaries.all():
            if beneficiary.is_recommended(self.id)[0]:
                self.grant_loan(beneficiary.user)
            else:
                self.deny_loan(beneficiary.user)
        return None

    def get_absolute_url(self):
        return reverse('loans:user-loan-details', args=[self.pk])


RECORD_CATEGORY = (('Purchase', 'Purchase'),
                   ('Expenses', 'Expenses'),
                   ('Tax', 'Tax'),
                   ('Income', 'Income'))


class Record(models.Model):
    amount = models.DecimalField(max_digits=12, decimal_places=2, default=0)
    date = models.DateTimeField(auto_now=True)
    category = models.CharField(max_length=45, choices=RECORD_CATEGORY, default='', verbose_name='Category')
    description = models.CharField(max_length=40)


class SalesRecord(models.Model):
    item_name = models.CharField(max_length=200, blank=False, null=True)
    quantity = models.PositiveIntegerField(default=1)
    cost_price_per_item = models.DecimalField(max_digits=12, decimal_places=2, default=0)
    selling_price_per_item = models.DecimalField(max_digits=12, decimal_places=2, default=0)
    date = models.DateTimeField(auto_now=True)

    def get_profit(self):
        total_costs = self.quantity * self.cost_price_per_item
        total_sales = self.quantity * self.selling_price_per_item

        print('total_sales : ' + str(total_sales))
        print('self.quantity : ' + str(self.quantity))
        print('self.cost_price_per_item : ' + str(self.cost_price_per_item))
        print('self.selling_price_per_item : ' + str(self.selling_price_per_item))
        print('total_costs : ' + str(total_costs))

        return total_sales - total_costs

    @property
    def get_total_sales(self):
        total_sales = self.quantity * self.selling_price_per_item

        return total_sales

    @property
    def get_total_cost(self):
        total = self.quantity * self.cost_price_per_item

        print('get_total_cost : ' + str(total))
        return total


class FinancialRecord(models.Model):
    user = models.ForeignKey(get_user_model(), on_delete=models.DO_NOTHING)
    profit = models.DecimalField(max_digits=12, decimal_places=2, verbose_name="Profit", default=0)
    net_profit = models.DecimalField(max_digits=12, decimal_places=2, default=0)
    revenue = models.DecimalField(max_digits=12, decimal_places=2, default=0)
    records = models.ManyToManyField(Record, blank=True)
    sales_records = models.ManyToManyField(SalesRecord, blank=True)

    def get_ideal_profit(self):

        print(self)

        profit = 0

        start_date = datetime.today()
        end_date = start_date - timedelta(days=30)

        print('end date : ' + str(end_date))
        print('start date : ' + str(start_date))

        all_sales_records = self.sales_records.all()

        # print(all_sales_records)
        all_sales_records.filter(date__gte=end_date).filter(date__lte=start_date)

        for sales_record in all_sales_records.filter(date__gte=end_date).filter(date__lte=start_date):
            profit += sales_record.get_profit()
            print('get_ideal_profit : ' + str(profit))

        return profit

    @property
    def get_total_expenses(self):

        total_expenses = 0
        start_date = datetime.today()
        end_date = start_date - timedelta(days=30)

        print('end date : ' + str(end_date))
        print('start date : ' + str(start_date))

        all_records = self.records.all()

        for record in all_records.filter(date__gte=end_date).filter(date__lte=start_date).exclude(category="Expenses"):

Users/models.py
from pyexpat import model
from django.db import models
from django.contrib.auth.models import AbstractUser
from phonenumber_field.modelfields import PhoneNumberField
from .validators import validate_phone_number


class Sector(models.Model):
    name = models.CharField(max_length=200)

    def __str__(self) -> str:
        return str(self.name)


# Create your models here.
TIME_IN_BUSINESS_CHOICES = (('Less than 1 year', 'Less than 1 year'),
                            ('2 years', '2 years'),
                            ('3 years', '3 years'),
                            ('4 years', '4 years'),
                            ('5 years', '5 years'),
                            ('Above 5 years', 'Above 5 years'),)
                            
BUSINESS_SIZE = (('MICRO', 'MICRO'), ('SMALL', 'SMALL'), ('MEDIUM', 'MEDIUM'),)

class User(AbstractUser):
    middle_name = models.CharField(max_length=100, blank=True, )
    phone = models.CharField(max_length=20, blank=False, unique=True, null=True)
    image = models.ImageField(default='default.png', upload_to='profile_photo/%Y/%m/%d/')
    is_verified = models.BooleanField(default=False)
    is_number_verified = models.BooleanField(default=False)
    reset_code = models.CharField(max_length=8, help_text='Enter code')
    is_kyc_verified = models.BooleanField(default=False)
    date_of_birth = models.DateTimeField(blank=True, null=True)
    address = models.TextField(max_length=200, blank=True, null=True)
    state = models.CharField(max_length=100, blank=True, null=True)
    occupation = models.CharField(max_length=100, blank=True, null=True)
    bvn = models.PositiveIntegerField(blank=False, null=True)
    nin = models.PositiveIntegerField(blank=False, null=True)
    business_certificate = models.FileField(upload_to='business_certificate/%Y/%m/', null=True, blank=True)
    financial_record = models.FileField(upload_to='financial_record/%Y/%m/', null=True, blank=True)
    balance_sheet = models.FileField(upload_to='financial_record/%Y/%m/', null=True, blank=True)
    time_in_business = models.CharField(max_length=30, choices=TIME_IN_BUSINESS_CHOICES, blank=True, null=True)
    sector = models.ForeignKey(Sector, on_delete=models.DO_NOTHING, blank=True, null=True)
    size = models.CharField(choices=BUSINESS_SIZE, max_length=20)
    number_of_employee = models.PositiveIntegerField(blank=True, null=True)
    
    class Meta:
        permissions = [('can_create_loans', 'Can Create Loans')]

 
    def validate_bvn(request):
        """this will be used to validate uses bvn"""
        pass

templates/fsp/beneficiary_data.html
{% extends 'fsp/fsp-base.html' %}
{% block title %}Lamuni:Loans{% endblock %}

{% block content %}
<div class="flex flex-col text-left m-10">
        <div class="-my-2 overflow-x-auto sm:-mx-6 lg:-mx-8">
                 <div class="flex flex-col  mt-10 sm:mt-0 w-full">
                    <!-- profile heading -->
                    <div class="shadow-md shadow-light-gray bg-white rounded-b-lg border-t-8 border-dark-green  px-4 sm:px-8">

                        <h1 class="font-medium text-3xl my-2">Applicats Details</h1>
                        <div class="flex flex-col space-y-4 p-8">
                        <p>First name: Ibrahim Muhammad Sadiq</p>
                             <p>Middle name: Muhammad </p>
                             <p>Last name: Sadiq</p>

                            <p>Phone: +2348128543654</p>
                            <p>Address: No. 234 Hotoro nasarawa LGA Kano Nigeria</p>
                         <p>Financial Statement:<a href="{% url "users:financial-statement" %}"></a> <button class="py-2 px-4 bg-green-500 text-white rounded hover:bg-green-600 active:bg-blue-700 disabled:opacity-50">Download</button></p>
                            <p>Balance Sheet:<a href="{%  url "users:financial-statement" %}"></a> <button class="py-2 px-4 bg-green-500 text-white rounded hover:bg-green-600 active:bg-blue-700 disabled:opacity-50">Download</button></p>
                        </div>

                    </div>

            </div>
          </div>
{% endblock %}

templates/fsp/create_loan.html
{#<form action="" method="post">#}
{#    {{ form.as_p }}#}
{#{% csrf_token %}#}
{#    <input type="submit">#}
{#</form>#}

{% extends 'fsp/fsp-base.html' %}
{% block title %}Lamuni:Create-Loan{% endblock %}
{% block content %}

    <div class="max-w-2xl bg-white mx-auto w-full mt-5">
        <div class="p-8 rounded border border-gray-200">
            <h1 class="font-medium text-3xl">Create Loan</h1>
            <p class="text-green-600 mt-6">Fill each field with the appropriate data</p>

            <form class="" method="post">
            {% csrf_token %}
              <div class="mt-8 grid grid-cols-1 gap-4">
                <p>
                <label for="id_program_title" class="text-sm text-gray-700 block mb-1 font-medium" >Program title:</label>
                <input class="bg-white border border-gray-200 rounded py-1 px-3 block focus:ring-green-500 focus:border-green-500 text-gray-700 w-full" type="text" name="program_title" maxlength="200" required id="id_program_title" placeholder="Enter your program name">
                     {{ form.program_title.errors }}
              </p>


                      <p>
                        <label  class="text-sm text-gray-700 block mb-1 font-medium">Size:</label>
                        <div id="id_size" class="grid sm:grid-cols-3">
                    <div>
                        <label for="id_size_0"><input class="accent-dark-green"  type="checkbox" name="size" value="MICRO" id="id_size_0">
                     MICRO</label>

                    </div>
                  <div>
                        <label for="id_size_1"><input class="accent-dark-green"  type="checkbox" name="size" value="SMALL" id="id_size_1">
                     SMALL</label>

                    </div>
                  <div>
                        <label for="id_size_2"><input class="accent-dark-green" type="checkbox" name="size" value="MEDIUM" id="id_size_2">
                     MEDIUM</label>

                    </div>
                    </div>
              </p>

                  <p >
                  <label  class="text-sm text-gray-700 block mb-1 font-medium">Sectors:</label>

{#                 <div id="id_sectors" class="grid sm:grid-cols-3">#}
                                     {{ form.sectors }}

                     {{ form.sectors.errors }}

                  </p>


{#            </div>#}
{#              </p>#}


                  <p>
    <label for="id_amount"  class="text-sm text-gray-700 block mb-1 font-medium">Amount:</label>
    <input type="number" name="amount" min="0" required id="id_amount" class="bg-white border border-gray-200 rounded py-1 px-3 block focus:ring-green-500 focus:border-green-500 text-gray-700 w-full" >


  </p>


  <p>
    <label for="id_paying_days"  class="text-sm text-gray-700 block mb-1 font-medium">Paying days:</label>
    <input type="number" name="paying_days" min="0" required id="id_paying_days" class="bg-white border border-gray-200 rounded py-1 px-3 block focus:ring-green-500 focus:border-green-500 text-gray-700 w-full" >


  </p>


  <p>
    <label for="id_grace_period"  class="text-sm text-gray-700 block mb-1 font-medium">Grace period:</label>
    <input type="number" name="grace_period" min="0" required id="id_grace_period" class="bg-white border border-gray-200 rounded py-1 px-3 block focus:ring-green-500 focus:border-green-500 text-gray-700 w-full" >


  </p>


  <p>
    <label for="id_collateral"  class="text-sm text-gray-700 block mb-1 font-medium">Collateral:</label>
    <input type="text" name="collateral" maxlength="200" id="id_collateral" class="bg-white border border-gray-200 rounded py-1 px-3 block focus:ring-green-500 focus:bg-dark-green focus:border-green-500 text-gray-700 w-full" >




  </p>
                    <p>
    <label for="id_requirements">Requirements:</label>
    {{ form.requirements }}

                     {{ form.requirements.errors }}



  </p>
                  <label for="id_intrest">Interest:</label>
                         {{ form.intrest }}
                     {{ form.intrest.errors }}



  </p>
    </div>

               <div class="flex flex-col space-y-4 sm:flex-row sm:space-y-0 sm:space-x-4 w-full mt-10 mb-5 justify-between">

              <div class="flex flex-col space-y-4 sm:flex-row sm:space-x-4 mt-8">
                <button type="submit" class="py-2 px-4 bg-green-500 text-white rounded hover:bg-green-600 active:bg-blue-700 disabled:opacity-50">Create Loan</button>
               </div>

            </form>
          </div>
    </div>

{% endblock %}

templates/fsp/dashboard.html
{% for loan in loans %}
<p>
    <a href="/fsp/loan-details/{{ loan.id }}">{{ loan.program_title }}</a>
</p>
{% endfor %}

templates/fsp/loan.html
{% extends 'fsp/fsp-base.html' %}
{% block title %}Laminu:Dashbord{% endblock %}

{% block content %}
        <!-- create Loan -->
        <div class=" flex flex-col space-y-4 md:space-y-0  md:space-x-4 md:flex-row justify-between my-5 sm:my-10 ">
            <form class="flex items-center rounded-lg shadow bg-dark-green max-w-xs">
                <input class="bg-white py-3 px-2 sm:p-6 rounded-lg focus:outline focus:outline-dark-green focus:border-dark-green hover:ring-1 ring-dark-green" type="search" name="loan" id="loan" placeholder="Search Loan">
                <button class="py-3 px-2 sm:p-6 text-white font-semibold text-sm sm:text-base" type="submit" value="search">Search</button>
            </form>

            <a href="{% url 'loans:create_loan' %}" >
            <div class=" bg-white rounded-lg shadow max-w-xs p-3 sm:p-6 hover:bg-gray-300">

                    <div class=" flex items-center justify-between space-x-4">
                        <h2 class=" text-xs sm:text-base text-gray-500">Create New Loan Program</h2>
                        <div class="">
                            <svg xmlns="http://www.w3.org/2000/svg" class="h-6 w-6 text-green-600" fill="none" viewBox="0 0 24 24" stroke="currentColor" stroke-width="2">
                                <path stroke-linecap="round" stroke-linejoin="round" d="M12 4v16m8-8H4" />
                              </svg>
                        </div>
                    </div>
            </div>
            </a>



        </div>
        <!-- end of create loan -->

        <div class="my-5 sm:my-10">
            <h1 class="text-lg sm:text-4xl text-dark-gray">List of Loans</h1>
        </div>

        <!-- loan table -->
        <div class="flex overflow-auto">
            <div class="flex flex-col">
                <div class="w-full">
                    <div class="border-b border-gray-200 shadow">
                        <table class="divide-y divide-gray-300 ">
                            <thead class="bg-gray-50">
                                <tr>
                                    <th class="px-6 py-2 text-xs text-gray-500">
                                        ID
                                    </th>
                                    <th class="px-6 py-2 text-xs text-gray-500">
                                        Program Title
                                    </th>
                                    <th class="px-6 py-2 text-xs text-gray-500">
                                        Size
                                    </th>
                                    <th class="px-6 py-2 text-xs text-gray-500">
                                        Sector
                                    </th>
                                    <th class="px-6 py-2 text-xs text-gray-500">
                                        Amount
                                    </th>
                                    <th class="px-6 py-2 text-xs text-gray-500">
                                        Applicants
                                    </th>
                                    <th class="px-6 py-2 text-xs text-gray-500">
                                        Active
                                    </th>
                                    <th class="px-6 py-2 text-xs text-gray-500">
                                        Paying Days
                                    </th><th class="px-6 py-2 text-xs text-gray-500">
                                       Grace period
                                    </th><th class="px-6 py-2 text-xs text-gray-500">
                                        Collateral
                                    </th>
                                </tr>
                            </thead>

                            {% for loan in loans %}
                            <tbody class="bg-white divide-y divide-gray-300">
                                <tr class="whitespace-nowrap">
                                    <td class="px-6 py-4 text-sm text-gray-500">
                                        1
                                    </td>
                                    <td class="px-6 py-4">
                                       <a href="{% url 'loans:loan_details' loan.id %}">
                                        <div class="text-sm text-gray-900 bg-gray-200 px-4 py-1 rounded-full">
                                            {{ loan.program_title }}
                                        </div>
                                       </a>
                                    </td>
                                    <td class="px-6 py-4">
                                        <div class="text-sm text-gray-500">medium</div>
                                    </td>
                                    <td class="px-6 py-4 text-sm text-gray-500">
                                        {% for sector in loan.sectors.all %}
                                        {{ sectors.name }}
                                            {% endfor %}
                                    </td>
                                    <td class="px-6 py-4 text-sm text-gray-500">
                                        {{ loan.amount }}
                                    </td>
                                    <td class="px-6 py-4">
                                        <a href="{% url 'loans:beneficiaries' loan.id %}">
                                         <div class="text-sm text-blue-900 bg-blue-200 px-4 py-1 rounded-full">
                                             {{ loan.beneficiaries.all.count }}
                                         </div>
                                        </a>
                                     </td>

                                    <td class="px-6 py-4 text-sm">
                                           {% if  loan.is_active %}
                                        <span class="px-4 py-1 text-green-600 bg-green-200 rounded-full">Yes</span>
                                        {% else %}
                                        <span class="px-4 py-1 text-red-600 bg-red-200 rounded-full">No</span>
                                            {% endif %}
                                    </td>

                                    <td class="px-6 py-4 text-sm text-gray-500">
                                        {{ loan.paying_days }}
                                    </td>
                                    <td class="px-6 py-4 text-sm text-gray-500">
                                       {{ loan.grace_period }}
                                    </td>
                                    <td class="px-6 py-4 text-sm text-gray-500">
                                        {{ loan.collateral }}
                                    </td>
                                </tr>



                            </tbody>
                            {% endfor %}
                        </table>
                    </div>
                </div>
            </div>
        </div>


          <!-- end loan table -->

{% endblock %}