Lamuni/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf.urls.i18n import i18n_patterns

urlpatterns = i18n_patterns(
    path('admin/', admin.site.urls),
    path("accounts/", include("Users.urls")),
    path("", include("Users.urls")),
    path("", include("Wallet.urls")),
    path("", include("Loans.urls")),
    path("accounts/", include("Users.urls")),
    path("fsp/", include("Loans.urls")),
    path('', include("Lessons.urls")),
    path('accounts/', include('django.contrib.auth.urls')),
    path('i18n/', include('django.conf.urls.i18n')),
    path('ckeditor/', include('ckeditor_uploader.urls')),
    # path('rosetta/', include('rosetta.urls')),
    prefix_default_language=True,
)

Lessons/urls.py
from django.urls import path
from .views import lesson_detail, lessons_list, mark_lesson_completed, quiz, quiz_list

app_name = 'lessons'

urlpatterns = [
    path('lessons/list/', lessons_list, name='lessons'),
    path('lesson/detail/<int:pk>/', lesson_detail, name='detail'),
    path('mark/completed/<int:pk>/', mark_lesson_completed, name='completed'),
    path('quiz/list/', quiz_list, name='quiz-list' ),
    path('quiz/<int:pk>/', quiz, name='quiz'),
]

Loans/urls.py
from django.urls import path
from .views import create_loan, loan_details, dashboard, loans_list, fsp_profile, \
    loan_beneficiaries, add_record, add_sales_record, fs, fr, user_loan_details, \
    list_loans, apply_loan, users_credentials, grant_loan, deny_loan, generate_income_statement, \
    request_financial_statements, verify_transfer, beneficiary_data

app_name = 'loans'

urlpatterns = [
    path('add/record/', add_record, name='add-record'),
    path('fs/', fs),
    path('fr/<int:pk>/', fr),
    path('add/sales/record/', add_sales_record, name='add-sales-record'),
    path('pdf/', generate_income_statement),
    # path('balance-sheet/', GenerateBalanceSheet.as_view()),
    path('create-loan/', create_loan, name="create_loan"),
    path('loan-details/<int:pk>/', loan_details, name="loan_details"),
    path('user-loan-details/<int:pk>/', user_loan_details, name="user-loan-details"),
    path('dashboard/', dashboard, name="dashboard"),
    path('loans/', loans_list, name='loans_list'),
    path('fsp/profile/', fsp_profile, name='profile'),
    path('loans/<int:pk>/beneficiaries/', loan_beneficiaries, name='beneficiaries'),
    path('loans/<int:loan_pk>/beneficiaries/<int:beneficiary_pk>', beneficiary_data, name='beneficiary_data'),
    path('list-loans', list_loans, name="list_loans"),
    path('apply-loan/<int:id>/', apply_loan, name="apply_loan"),
    path('users-credential/<int:loan_id>/<slug:username>/', users_credentials, name="users_loan_requirements"),
    path('grant-loan/<int:loan_id>/<slug:username>/', grant_loan, name="approve_loan"),
    path('deny-loan/<int:loan_id>/<slug:username>/', deny_loan, name="deny_loan"),
    path('request-financial-statement/', request_financial_statements, name="request-statement"),
    path('transfer/verify', verify_transfer, name="verify_transfer"),
    # path("recommended-loans/", recommended_loans, name="recommended_loans")
]

Users/urls.py
from .views import (chating, index, register,verify_code, send_reset_code, reset_verify,
    reset_password, education,lesson_detail, lesson_done,  user_profile, conversation, financial_statement,
    update_user_profile,  verification)

from django.contrib.auth import views as auth_views
from django.urls import path

app_name = "users"

urlpatterns = [
    path("", index, name="index"),
    path("signup/", register, name="signup"),
    path('logout/', auth_views.LogoutView.as_view(template_name='registration/logout.html')),
    path('verify/<slug:username>/', verify_code, name="verify"),  # ← new
    path('send_reset/', send_reset_code, name="reset_code"),
    path('reset_verify/<slug:username>/', reset_verify, name="reset_verify"),
    path('password_reset/<slug:username>/<int:code>/', reset_password, name="reset_password"),
    path('profile/', user_profile, name="profile"),
    path('profile/update', update_user_profile, name="update_profile"),
    path("bot/", chating, name="bot"),
    path("conversation/", conversation, name="conversation"),
    path("financial-statement/", financial_statement, name="financial-statement"), 
    path('verify/', verification, name="verify")
]

Wallet/urls.py
from django.urls import path
from .views import view_wallet, recharge, withdraw, transfer

app_name = 'wallets'

urlpatterns = [
    path('wallet/', view_wallet, name='index'),
    path('wallet/recharge/', recharge, name='recharge'),
    path('wallet/withdraw/', withdraw, name='withdraw'),
    path('wallet/transfer/', transfer, name='transfer')
]

Users/models.py
from pyexpat import model
from django.db import models
from django.contrib.auth.models import AbstractUser
from phonenumber_field.modelfields import PhoneNumberField
from .validators import validate_phone_number


class Sector(models.Model):
    name = models.CharField(max_length=200)

    def __str__(self) -> str:
        return str(self.name)


# Create your models here.
TIME_IN_BUSINESS_CHOICES = (('Less than 1 year', 'Less than 1 year'),
                            ('2 years', '2 years'),
                            ('3 years', '3 years'),
                            ('4 years', '4 years'),
                            ('5 years', '5 years'),
                            ('Above 5 years', 'Above 5 years'),)
                            
BUSINESS_SIZE = (('MICRO', 'MICRO'), ('SMALL', 'SMALL'), ('MEDIUM', 'MEDIUM'),)

class User(AbstractUser):
    middle_name = models.CharField(max_length=100, blank=True, )
    phone = models.CharField(max_length=20, blank=False, unique=True, null=True)
    image = models.ImageField(default='default.png', upload_to='profile_photo/%Y/%m/%d/')
    is_verified = models.BooleanField(default=False)
    is_number_verified = models.BooleanField(default=False)
    reset_code = models.CharField(max_length=8, help_text='Enter code')
    is_kyc_verified = models.BooleanField(default=False)
    date_of_birth = models.DateTimeField(blank=True, null=True)
    address = models.TextField(max_length=200, blank=True, null=True)
    state = models.CharField(max_length=100, blank=True, null=True)
    occupation = models.CharField(max_length=100, blank=True, null=True)
    bvn = models.PositiveIntegerField(blank=False, null=True)
    nin = models.PositiveIntegerField(blank=False, null=True)
    business_certificate = models.FileField(upload_to='business_certificate/%Y/%m/', null=True, blank=True)
    financial_record = models.FileField(upload_to='financial_record/%Y/%m/', null=True, blank=True)
    balance_sheet = models.FileField(upload_to='financial_record/%Y/%m/', null=True, blank=True)
    time_in_business = models.CharField(max_length=30, choices=TIME_IN_BUSINESS_CHOICES, blank=True, null=True)
    sector = models.ForeignKey(Sector, on_delete=models.DO_NOTHING, blank=True, null=True)
    size = models.CharField(choices=BUSINESS_SIZE, max_length=20)
    number_of_employee = models.PositiveIntegerField(blank=True, null=True)
    
    class Meta:
        permissions = [('can_create_loans', 'Can Create Loans')]

 
    def validate_bvn(request):
        """this will be used to validate uses bvn"""
        pass

Users/forms.py
from dataclasses import fields
from pyexpat import model
from django import forms
from django.forms import ModelForm
from django.contrib.auth.forms import UserCreationForm, UserChangeForm
from django.forms import SelectDateWidget

from .models import User


class CustomUserCreationForm(UserCreationForm):
    phone = forms.CharField(max_length=20, required=True, help_text='Phone number')

    class Meta:
        model = User
        fields = ("username", "first_name", "middle_name", "last_name", "phone")


class CustomUserChangeForm(UserChangeForm):
    class Meta:
        model = User
        fields = ("username", "first_name", "middle_name", "last_name", "phone")


class UserEditForm(forms.ModelForm):
    class Meta:
        model = User
        fields = (
        'image', 'first_name', 'middle_name', 'last_name', 'email', 'date_of_birth', 'phone', 'state', 'occupation')

    def __init__(self, *args, **kwargs):
        super(UserEditForm, self).__init__(*args, **kwargs)
        self.fields['date_of_birth'].widget = SelectDateWidget(
            empty_label=("Choose Year", "Choose Month", "Choose Day"))
        self.fields['image'].widget.attrs['class'] = 'form-input'
        self.fields['first_name'].widget.attrs['class'] = 'form-input'
        self.fields['middle_name'].widget.attrs['class'] = 'form-input'
        self.fields['last_name'].widget.attrs['class'] = 'form-input'
        self.fields['email'].widget.attrs['class'] = 'form-input'
        self.fields['date_of_birth'].widget.attrs['class'] = 'form-input'
        self.fields['phone'].widget.attrs['class'] = 'form-input'
        self.fields['state'].widget.attrs['class'] = 'form-input'
        self.fields['occupation'].widget.attrs['class'] = 'form-input'


# class ProfileForm(forms.ModelForm):
#     class Meta:
#         model = Profile
#         fields = ['image', 'date_of_birth']

class VerifyForm(forms.Form):
    code = forms.CharField(max_length=8, required=True, help_text='Enter code')


class SendResetCodeForm(forms.Form):
    phone = forms.CharField(max_length=20, required=True, help_text='Phone number')


class ResetPawsswordForm(forms.Form):
    password1 = forms.CharField(max_length=128)
    password2 = forms.CharField(max_length=128)


class KYCVerifyForm(ModelForm):
    class Meta:
        model = User
        fields = ("address", "bvn", "nin",
                  "time_in_business", "sector", "size", "number_of_employee")

    def __init__(self, *args, **kwargs):
        super(KYCVerifyForm, self).__init__(*args, **kwargs)
        self.fields['address'].widget.attrs['class'] = 'form-input'
        self.fields['bvn'].widget.attrs['class'] = 'form-input'
        self.fields['nin'].widget.attrs['class'] = 'form-input'
        self.fields['time_in_business'].widget.attrs['class'] = 'form-input'
        self.fields['sector'].widget.attrs['class'] = 'form-input'
        self.fields['size'].widget.attrs['class'] = 'form-input'
        self.fields['number_of_employee'].widget.attrs['class'] = 'form-input'

Wallet/forms.py
from django import forms
from .models import Transaction


class RechargeWallet(forms.ModelForm):
    class Meta:
        model = Transaction
        fields = ['amount', 'description']

    def clean_amount(self):
        if self.cleaned_data['amount'] == 0:
            self.add_error('amount', 'The field "Amount" should not be greater than 0.')
        else:
            return self.cleaned_data['amount']


class WithdrawWallet(forms.ModelForm):
    class Meta:
        model = Transaction
        fields = ['amount', 'description']

    def clean_amount(self):
        if self.cleaned_data['amount'] == 0:
            self.add_error('amount', 'The field "Amount" should not be greater than 0.')
        else:
            return self.cleaned_data['amount']


class TransferMoney(forms.ModelForm):
    class Meta:
        model = Transaction
        fields = ['amount', 'receiver', 'description']

    def clean_amount(self):
        if self.cleaned_data['amount'] == 0:
            self.add_error('amount', 'The field "Amount" should not be greater than 0.')
        else:
            return self.cleaned_data['amount']

Wallet/views.py
from django.http import HttpResponseRedirect, HttpResponse
from django.shortcuts import render
from django.shortcuts import get_object_or_404
from .forms import RechargeWallet, WithdrawWallet, TransferMoney
from .models import Wallet, wallet_ref_code_generator
from django.template import loader
from django.contrib.auth.decorators import login_required
import json
import requests
from django.conf import settings


# Create your views here
@login_required
def view_wallet(request):
    user = request.user

    try:
        wallet = Wallet.objects.get(owner=user)

    except Exception:

        wallet = Wallet.objects.create(
            owner=user,
            owner_type="User", )
    headers = {
        "Authorization": "dskjdks",
        "Content-Type": "application/json",
        "sandbox-key": settings.SANDBOX_KEY
    }
    url = "https://fsi.ng/api/v1/flutterwave/v3/virtual-account-numbers"
    data = ({
        "email": user.email,
        "is_permanent": True,
        "bvn": user.bvn,
        "amount": 500,
        "phonenumber": user.phone,
        "firstname": user.first_name,
        "lastname": user.last_name,
        "narration": "Lamuni",
    })

    my_data = requests.post(url=url, json=data, headers=headers)

    if my_data.status_code not in [200, 203]:
        message = "There was an error creating account number : {}:{}".format(
            my_data.status_code, my_data.text
        )
        print(message)

        data = {
            "message": message
        }
        return render(request, 'add_sales_record.html', context=data)

    json_data = my_data.json()

    real_data = json_data['data']

    wallet.account_number = real_data['account_number']
    wallet.account_name = real_data['note']
    wallet.bank = real_data['bank_name']

    wallet.save()

    template = loader.get_template('wallet_cabinet.html')

    # fill_up_wallet_form = RechargeWallet()
    # withdraw_money_form = WithdrawWallet()
    context = {
        'wallet': wallet,
        # 'fillUp_wallet_form': fill_up_wallet_form,
        # 'withdraw_money_form': withdraw_money_form
    }

    return HttpResponse(template.render(context, request))


def recharge(request, *args, **kwargs):
    if request.method == "POST":
        recharge_form = RechargeWallet(request.POST)
        if recharge_form.is_valid():
            owner = request.user
            amount = recharge_form.cleaned_data['amount']
            description = recharge_form.cleaned_data['description']
            ref_code = wallet_ref_code_generator()
            # payment = pay_with_pay_stack(request, amount, ref_code)
            recharge_transaction = Wallet.recharge_wallet(amount, owner, description)
            return HttpResponseRedirect('/wallet/')

    else:
        recharge_form = RechargeWallet()

    context = {
        'recharge_form': recharge_form
    }
    return render(request, 'user/recharge_form.html', context)


def withdraw(request, *args, **kwargs):
    if request.method == "POST":
        withdraw_form = WithdrawWallet(request.POST)
        if withdraw_form.is_valid():
            owner = request.user
            amount = withdraw_form.cleaned_data['amount']
            description = withdraw_form.cleaned_data['description']
            wallet_to_withdraw = get_object_or_404(Wallet, owner=owner)
            withdraw_transaction = Wallet.withdraw_wallet(amount, description, wallet_to_withdraw)
            return HttpResponseRedirect('/wallet/')

    else:
        withdraw_form = WithdrawWallet()

    context = {
        "withdraw_form": withdraw_form
    }
    return render(request, 'withdraw_form.html', context)


def transfer(request, *args, **kwargs):
    if request.method == "POST":
        transfer_form = TransferMoney(request.POST)
        sender = request.user
        if transfer_form.is_valid():
            amount = transfer_form.cleaned_data['amount']
            description = transfer_form.cleaned_data['description']
            receiver = transfer_form.cleaned_data['receiver']
            wallet_to_transfer = get_object_or_404(Wallet, owner=receiver)
            transfer_transaction = Wallet.transfer_money(amount, sender, receiver, description)
            return HttpResponseRedirect('/wallet/')

    else:
        transfer_form = TransferMoney()

    context = {
        "transfer_form": transfer_form,
    }
    return render(request, "user/transfer_form.html", context)

templates/add_sales_record.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Add Record</title>
</head>
<body>
<form method="post" action="">
    {% csrf_token %}
    {{ add_sales_form.as_p }}
    <input type="submit" value="Add Sales Record">
</form>
</body>
</html>

templates/base.html
<!DOCTYPE html>
{% load static %}
{%  load i18n %}
<html lang="en">
  <head>
    <meta charset="UTF-8" />
    <meta http-equiv="X-UA-Compatible" content="IE=edge" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <link rel="stylesheet" href="{% static 'css/index.css' %}" />
    <title>{% block title %}{% endblock %}</title>
  </head>
  <body >
    <!-- Header -->
    {% include 'components/header.html' %}
    <!-- Hero Section -->
    {% block content %} {% endblock %}
    <!-- Footer÷\ -->
    {% include 'components/footer.html' %}

    <script src="{% static 'js/index.js' %}" type="text/javascript"></script>
  </body>
</html>

templates/edit_profile.html
{% extends 'base.html' %}

{% block content %}
       <section class="container mx-auto">
        <div class="flex flex-col md:flex-row sm:space-x-6 my-5 sm:my-10 px-4 sm:px-8 text-dark-black  max-w-[1280px]">
                 <!-- Profile section -->
                 <div class="flex flex-col  mt-10 sm:mt-0 md:w-3/5 mx-auto">
                    <!-- profile heading -->
                    <div class="shadow-md shadow-light-gray bg-white rounded-b-lg border-t-8 border-dark-green  px-4 sm:px-8">
                        <form method="post">
                            <div class="mt-8 grid grid-cols-1 gap-4">
                                    {% csrf_token %}
                                    <p>
    <label for="id_image" class="text-sm text-gray-700 block mb-1 font-medium">Image:</label>
     {{ form.image }}

    {{ form.image.errors }}

  </p>


  <p>
    <label for="id_first_name" class="text-sm text-gray-700 block mb-1 font-medium">First name:</label>
     {{ form.first_name }}

 {{ form.first_name.errors }}
  </p>


  <p>
    <label for="id_middle_name" class="text-sm text-gray-700 block mb-1 font-medium">Middle name:</label>
    {{ form.middle_name }}

 {{ form.middle_name.errors }}
  </p>


  <p>
    <label for="id_last_name" class="text-sm text-gray-700 block mb-1 font-medium">Last name:</label>
    {{ form.last_name }}
 {{ form.last_name.errors }}

  </p>


  <p>
    <label for="id_email" class="text-sm text-gray-700 block mb-1 font-medium">Email address:</label>
  {{ form.email }}

 {{ form.email.errors }}
  </p>


   <p>
    <label for="id_date_of_birth_month" class="text-sm text-gray-700 block mb-1 font-medium">Date of birth:</label>
   {{ form.date_of_birth}}
       {{ form.date_of_birth.errors }}


  </p>



  <p>
    <label for="id_phone" class="text-sm text-gray-700 block mb-1 font-medium">Phone:</label>

 {{ form.phone }}
       {{ form.phone.errors }}
  </p>


  <p>
    <label for="id_state" class="text-sm text-gray-700 block mb-1 font-medium">State:</label>
       {{ form.state }}

 {{ form.state.errors }}

  </p>


  <p>
    <label for="id_occupation" class="text-sm text-gray-700 block mb-1 font-medium">Occupation:</label>
   {{ form.occupation }}


 {{ form.occupation.errors }}

  </p>

                            <div class="flex flex-col space-y-4 sm:flex-row sm:space-y-0 sm:space-x-4 w-full my-5 justify-between">
                <!-- Secondary -->
 <button class="py-2 px-8 bg-white border border-gray-200 text-green-600 rounded hover:bg-white active:bg-gray-200 disabled:opacity-50"  onclick="history.go(-1)">Cancel</button>
                                 <button type="submit" class="py-2 px-4 bg-green-500 text-white rounded hover:bg-green-600 active:bg-blue-700 disabled:opacity-50">Update Profile</button>
              </div>
                                </div>

                        </form>
                    </div>


        </div>
       </section>
{% endblock %}

templates/lesson-detail.html
{% extends "education_base.html" %} {% load static %}
{% block title %} {{lesson.title}}{% endblock %}
{% block content %}
<link rel="stylesheet" href="https://fonts.googleapis.com/css2?family=Poppins:wght@100;200;300;400;500;600;700&display=swap">
<style>

    body {
        font-family: Poppins;
    }
    h1 { 
        font-size: 2em;
     }
    h2 { 
        font-size: 1.5em; 
    }
    h3 { font-size: 1.17em; }
    h4 { font-size: 1.12em; }
    h5 { font-size: .83em; }
    h6 { font-size: .75em; }
</style>
    <!-- main blog -->


    <section class="container mx-auto max-w-[950px] px-8">
        {{lesson.blog|safe}}

                    <!-- tags -->

        <div class="flex justify-start items-center text-white space-x-4 my-10 flex-wrap">
            {% for tag in lesson.tags.all %}
            <div class="my-2">
                <button class="bg-dark-green px-4 md:px-6 py-2 rounded-full shadow-inner hover:bg-green-700">{{ tag }}</button>
            </div>
            {% endfor %}
        </div>



        
        
    </section>
    <section class="container mx-auto flex justify-center sm:justify-end px-8 my-10 ">

          <a  href="{%  url 'lessons:completed' lesson.id %}" class=""> <button type="submit" class="flex items-center text-dark-green hover:bg-dark-green hover:text-white border-[1px] border-dark-green px-3 py-2 rounded-md space-x-2">
            <span>
                <svg xmlns="http://www.w3.org/2000/svg" class="h-8 w-8" fill="none" viewBox="0 0 24 24" stroke="currentColor" stroke-width="2"><path stroke-linecap="round" stroke-linejoin="round" d="M9 12l2 2 4-4m6 2a9 9 0 11-18 0 9 9 0 0118 0z" /></svg>
            </span>Mark As Read</button></a>

    </section>

    {% endblock %}

templates/lesson-done.html
{% extends 'education_base.html' %}

{% block title %}Lamuni:Lesson Done{% endblock %}
{% block content %}
       <section class="container mx-auto max-w-[950px] my-10 px-8 text-dark-black">
        <div class="flex flex-col items-center justify-between space-y-12 border-2 rounded-md p-10 bg-white shadow-lg shadow-light-gray my-5">
            <div class="">
                <p class="text-lg sm:text-3xl text-dark-green">Lesson {{ lesson.id }} Completed</p>
            </div>
            <div>
                <p class="text-base sm:text-2xl text-dark-black">Comment: Nice Keep It Up</p>
            </div>
            <a class="block" href="{{ lesson.get_quiz_url }}"><button class="sm:px-6 py-2 px-4 sm:py-4 border-2 border-dark-green text-dark-green  hover:bg-dark-green focus:bg-dark-green hover:text-white focus:text-white font-bold rounded-md">Take Quiz</button></a>

        </div>

        <div class="my-20 flex items-center justify-between">
            <a href="{{ lesson.get_absolute_url }}"><button class="sm:px-6 py-2 px-4 sm:py-4 border-2 border-dark-green text-dark-green  hover:bg-dark-green focus:bg-dark-green hover:text-white focus:text-white font-bold rounded-md">Read Again</button></a>
            <a href="{% url 'lessons:lessons' %}"><button class="sm:px-6 py-2 px-4 sm:py-4 border-2 border-dark-green text-dark-green  hover:bg-dark-green focus:bg-dark-green hover:text-white focus:text-white font-bold rounded-md">Next Lesson</button></a>
        </div>
    </section>

{% endblock %}

templates/login.html
<!DOCTYPE html>
{% load static %}
<html lang="en">
<head>
    <meta charset="UTF-8">
     <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <link rel="stylesheet" href="{% static 'css/index.css' %}">
    <title>Lamuni:LogIn</title>
</head>
<body>
    {% include 'components/header.html' %}

    <section >
        <div class="flex flex-col md:flex-row md:space-x-12 px-6 md:px-0">
            <div class=" hidden md:block bg-dark-green text-dark-green w-1/2 ">
                <div class=" hidden sm:flex flex-col py-16  items-center">
                    <img class="w-4/5" src="{% static '/img/photo/planting.jpeg' %}" alt="image">
                </div>
                
                <!-- <div class="flex flex-col items-center justify-center -mt-12 ">
                    <h3 class="text-white font-bold text-xl sm:text-4xl">Unparalleled templates </h3>
                    <p class="text-white font-light text-sm sm:text-base text-center max-w-sm mb-2"> Crafted by a team of professional designers, our templates are unparalleled n the market.</p>

                    <div class="flex space-x-2">
                        <div class="bg-white h-3 w-3 rounded-full"></div>
                        <div class="bg-light-gray h-3 w-3 rounded-full"></div>
                        <div class="bg-light-gray h-3 w-3 rounded-full"></div>
                        <div class="bg-light-gray h-3 w-3 rounded-full"></div>
                    </div>

                </div>

 -->

            </div>
            <!-- login form -->
            <div class="flex flex-col space-y-6 md:px-12 lg:px-20 py-12  bg-white md:w-1/2">
                <h1 class="text-3xl lg:text-4xl font-bold">Log-in to your Lamuni account</h1>
                <div class="flex flex-col space-y-4">
                    <div class="flex flex-col space-y-4">
                        <label class="text-xl" for="name">Phone Number</label>
                        <input class="px-3 py-3 border border-light-gray rounded-md focus:text-dark-gray focus:outline-dark-green"  placeholder="+23428543654" type="number" name="" id="number">
                       
                    </div>
                    <div class="flex flex-col space-y-4">
                        <label class="text-xl" for="name">Password</label>
                        <input class="px-3 py-3 border border-light-gray rounded-md text-light-gray focus:outline-dark-green" placeholder="At least 8 characters" type="password" name="password" id="password" >
                    </div>
                </div>
                <div class="flex items-center justify-between text-sm md:text-base">
                    <div class=" flex items-center ">
                        <input class="h-5 w-5 border-light-gray accent-dark-green mr-1" type="checkbox" name="check" id="check">
                        <p>Remember me</p>
                     </div>
                     <p class="">
                        Forgot Password ?
                     </p>
                </div>
                    <button class="px-6 py-4 bg-dark-green text-white font-bold rounded-md"><a href="#">Log In</a></button>
                <button class="px-6 py-4 bg-darktext-dark-green text-white font-bold rounded-md"><a href="#">Create Fiber Account</a></button>
                <div class="flex items-center justify-center">
                    <p class="text-lg">Don't have an account? <a href="{% url 'users:signup' %}" class="font-bold text-dark-green">Sign Up</a></p>
                </div>

            </div>

            <!-- Image -->
          
        </div>
    </section>
    {% include 'components/footer.html' %}
    <script src="{% static 'js/index.js' %}" type="text/javascript"></script>

</body>
</html>

templates/wallet.html
<!DOCTYPE html>
{% load i18n %}
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Wallet</title>
</head>
<body>

<h1> {{wallet.balance}}</h1>
<h2> {{wallet.owner_type}}</h2>
<h3> {{wallet.owner.name}}</h3>
<h3> Last transaction date : {{wallet.date_updated}}</h3>
</body>
</html>

templates/wallet_cabinet.html
<!DOCTYPE html>
<html lag="en">
<head>
    <meta charset=UTF-8>
    <title>

    </title>
    <link rel="stylesheet" href="bootstrap-4.3.1-dist\css\bootstrap.min.css">
    <link rel="stylesheet" href="fontawesome-free-5.14.0-web\css\all.css">
    <link rel="stylesheet" href="https://ajax.aspnetcdn.com/ajax/bootstrap/4.3.1/css/bootstrap.min.css ">
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/5.14.0/css/all.css">
</head>
<body>
<p> Time:{% now "jS F Y H:i" %}</p>
<h1>Wallet Dashboard</h1><br/>
Hello, {{ wallet.owner }}!<br/>
<hr/>
<div class="col-sm-12">
    <h2>Wallet balance: {{ wallet.balance }}</h2><br>
</div>
<hr/>

<h2>Recharge wallet</h2>
{% url 'wallet:recharge' wallet.slug as recharge_url %}
<a href="{{ recharge_url }}">Recharge</a>
<hr/>
<h2>Withdraw Money</h2>
{% url 'wallet:withdraw' wallet.slug as withdraw_url %}
<a href="{{ withdraw_url }}">Withdraw</a>
<hr/>
<h2>Transfer Money </h2>
{% url 'wallet:transfer' wallet.slug as transfer_url %}
<a href="{{ transfer_url }}">Transfer</a>


</body>
</html>