Lamuni/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf.urls.i18n import i18n_patterns

urlpatterns = i18n_patterns(
    path('admin/', admin.site.urls),
    path("accounts/", include("Users.urls")),
    path("", include("Users.urls")),
    path("", include("Wallet.urls")),
    path("", include("Loans.urls")),
    path("accounts/", include("Users.urls")),
    path("fsp/", include("Loans.urls")),
    path('', include("Lessons.urls")),
    path('accounts/', include('django.contrib.auth.urls')),
    path('i18n/', include('django.conf.urls.i18n')),
    path('ckeditor/', include('ckeditor_uploader.urls')),
    # path('rosetta/', include('rosetta.urls')),
    prefix_default_language=True,
)

Lessons/urls.py
from django.urls import path
from .views import lesson_detail, lessons_list, mark_lesson_completed, quiz, quiz_list

app_name = 'lessons'

urlpatterns = [
    path('lessons/list/', lessons_list, name='lessons'),
    path('lesson/detail/<int:pk>/', lesson_detail, name='detail'),
    path('mark/completed/<int:pk>/', mark_lesson_completed, name='completed'),
    path('quiz/list/', quiz_list, name='quiz-list' ),
    path('quiz/<int:pk>/', quiz, name='quiz'),
]

Loans/urls.py
from django.urls import path
from .views import create_loan, loan_details, dashboard, loans_list, fsp_profile, \
    loan_beneficiaries, add_record, add_sales_record, fs, fr, user_loan_details, \
    list_loans, apply_loan, users_credentials, grant_loan, deny_loan, generate_income_statement, \
    request_financial_statements, verify_transfer, beneficiary_data

app_name = 'loans'

urlpatterns = [
    path('add/record/', add_record, name='add-record'),
    path('fs/', fs),
    path('fr/<int:pk>/', fr),
    path('add/sales/record/', add_sales_record, name='add-sales-record'),
    path('pdf/', generate_income_statement),
    # path('balance-sheet/', GenerateBalanceSheet.as_view()),
    path('create-loan/', create_loan, name="create_loan"),
    path('loan-details/<int:pk>/', loan_details, name="loan_details"),
    path('user-loan-details/<int:pk>/', user_loan_details, name="user-loan-details"),
    path('dashboard/', dashboard, name="dashboard"),
    path('loans/', loans_list, name='loans_list'),
    path('fsp/profile/', fsp_profile, name='profile'),
    path('loans/<int:pk>/beneficiaries/', loan_beneficiaries, name='beneficiaries'),
    path('loans/<int:loan_pk>/beneficiaries/<int:beneficiary_pk>', beneficiary_data, name='beneficiary_data'),
    path('list-loans', list_loans, name="list_loans"),
    path('apply-loan/<int:id>/', apply_loan, name="apply_loan"),
    path('users-credential/<int:loan_id>/<slug:username>/', users_credentials, name="users_loan_requirements"),
    path('grant-loan/<int:loan_id>/<slug:username>/', grant_loan, name="approve_loan"),
    path('deny-loan/<int:loan_id>/<slug:username>/', deny_loan, name="deny_loan"),
    path('request-financial-statement/', request_financial_statements, name="request-statement"),
    path('transfer/verify', verify_transfer, name="verify_transfer"),
    # path("recommended-loans/", recommended_loans, name="recommended_loans")
]

Users/urls.py
from .views import (chating, index, register,verify_code, send_reset_code, reset_verify,
    reset_password, education,lesson_detail, lesson_done,  user_profile, conversation, financial_statement,
    update_user_profile,  verification)

from django.contrib.auth import views as auth_views
from django.urls import path

app_name = "users"

urlpatterns = [
    path("", index, name="index"),
    path("signup/", register, name="signup"),
    path('logout/', auth_views.LogoutView.as_view(template_name='registration/logout.html')),
    path('verify/<slug:username>/', verify_code, name="verify"),  # ← new
    path('send_reset/', send_reset_code, name="reset_code"),
    path('reset_verify/<slug:username>/', reset_verify, name="reset_verify"),
    path('password_reset/<slug:username>/<int:code>/', reset_password, name="reset_password"),
    path('profile/', user_profile, name="profile"),
    path('profile/update', update_user_profile, name="update_profile"),
    path("bot/", chating, name="bot"),
    path("conversation/", conversation, name="conversation"),
    path("financial-statement/", financial_statement, name="financial-statement"), 
    path('verify/', verification, name="verify")
]

templates/components/footer.html
<footer class="bg-light-orange mt-10">
    <div
      class="container mx-auto px-8 py-12 flex space-y-6 sm:space-y-0 justify-between flex-col sm:flex-row sm:space-x-6"
    >
      <div class="flex flex-col space-y-8 max-w-sm">
        <div>
          <h2 class="text-xl font-bold">Lamuni</h2>
          <p class="text-xs md:text-sm text-dark-gray tracking-wide">
            With Lamuni Fsp Can Create Credit Programs For MSME's setting custom requirements and having ability to access applicants data statistically and make smart decisions
          </p>
        </div>
        <p class="text-lg text-dark-gray">
          Made with
          <span class="inline-flex items-baseline"
            ><svg
              xmlns="http://www.w3.org/2000/svg"
              class="h-5 w-5"
              viewBox="0 0 20 20"
              fill="currentColor"
            >
              <path
                fill-rule="evenodd"
                d="M3.172 5.172a4 4 0 015.656 0L10 6.343l1.172-1.171a4 4 0 115.656 5.656L10 17.657l-6.828-6.829a4 4 0 010-5.656z"
                clip-rule="evenodd"
              /></svg
          ></span>
          in Kano,Nigeria.
        </p>
      </div>

      <div class="flex flex-col space-y-2">
        <h2 class="md:text-lg font-bold">Site Map</h2>
        <a href="#" class="text-xs md:text-sm text-dark-gray"> Home Page</a>
        <a href="#" class="text-xs md:text-sm text-dark-gray"> Pricing</a>
        <a href="#" class="text-xs md:text-sm text-dark-gray">
          Testimonials</a
        >
        <a href="#" class="text-xs md:text-sm text-dark-gray"> Features</a>
      </div>

      <div class="flex flex-col space-y-2 md">
        <h2 class="md:text-lg font-bold">Resources</h2>
        <a href="#" class="text-xs md:text-sm text-dark-gray">Support</a>
        <a href="#" class="text-xs md:text-sm text-dark-gray">Contact</a>
        <a href="#" class="text-xs md:text-sm text-dark-gray"> FAQ</a>
      </div>

      <div class="flex flex-col space-y-2">
        <h2 class="md:text-lg font-bold">Company</h2>
        <a href="#" class="text-xs md:text-sm text-dark-gray">About</a>
        <a href="#" class="text-xs md:text-sm text-dark-gray"> Customers</a>
        <a href="#" class="text-xs md:text-sm text-dark-gray">Blog</a>
      </div>

      <div class="flex flex-col space-y-2">
        <h2 class="md:text-lg font-bold">Portfolio</h2>
        <a href="#" class="text-xs md:text-sm text-dark-gray">
          Abubakar Muhd</a
        >
        <a href="#" class="text-xs md:text-sm text-dark-gray"
          >Auwal Abubakar
        </a>
        <a href="#" class="text-xs md:text-sm text-dark-gray">
          Bukhari Auwal</a
        >
      </div>
    </div>
  </footer>

templates/components/header.html
<header class="bg-white mb-10">
  <nav
    class="container mx-auto px-8 py-4 flex sm:space-x-6 items-center justify-between"
  >
      <a href="{% url 'users:index' %}"><h1 class="font-bold text-xl text-dark-green md:text-2xl">Lamuni</h1></a>

    <ul
      class="nav-menu first-letter flex flex-col absolute top-16 -left-full bg-white w-full text-left shadow-md sm:shadow-none border-b-2 border-light-orange sm:border-0 transition-all duration-300 mx-auto sm:w-auto sm:flex-row sm:static sm:space-x-6 items-center justify-between"
    >
      <li class="sm:mx-4 my-2">
        <a href="{% url 'loans:dashboard' %}" class="font-bold text-sm hover:text-dark-green">Loan</a>
      </li>
      <li class="sm:mx-4 my-2">
        <a
          href="{% url 'lessons:lessons' %}"
          class="font-bold text-sm hover:text-dark-green"
          >Education</a
        >
      </li>

      <li class="sm:mx-4 my-2">
        <a class="font-bold text-sm hover:text-dark-green">About Us</a>
      </li>
{% if request.user.is_authenticated %}
<li class="sm:mx-4 my-2">
<a href="{% url 'users:profile' %}" class="font-bold text-sm hover:text-dark-green">Profile</a>
</li>

<a href="{% url 'logout' %}" class="font-bold text-sm lg:text-base"
  ><button
class="sm:hidden px-4 py-2 text-white bg-dark-green rounded-md hover:bg-green-700 my-2"
>Logout</button></a
>

{% else %}

<a href="{% url 'login' %}" class="font-bold text-sm lg:text-base"
  ><button
class="sm:hidden px-4 py-2 rounded-md hover:text-dark-green my-2"
>Sign In</button></a
>

<a href="/accounts/signup" class="font-bold text-sm lg:text-base"
  ><button
class="sm:hidden text-white bg-dark-green px-4 hover:bg-green-700 py-2 rounded-md my-2"
>Sign Up</button></a
>

{% endif %}
    </ul>

    <div class="hidden sm:flex space-x-6">
     {% if request.user.is_authenticated %}

    <a href="{% url 'logout' %}" class="font-bold text-sm lg:text-base">
        <button class="px-4 py-2 text-white bg-dark-green rounded-md hover:bg-green-700 my-2">Logout</button></a>

     {% else %}

      <a href="{% url 'login' %}" class="font-bold text-sm lg:text-base"
      ><button class="px-4 py-2 rounded-md hover:text-dark-green">Sign In</button></a
      >

      <a
        href="{% url 'users:signup' %}"
        class="font-bold text-sm lg:text-base"
        ><button
      class="text-white bg-dark-green px-4 hover:bg-green-700 py-2 rounded-md"
      >Sign Up</button></a
      >

    {% endif %}
    </div>
    <div class="block hamburger cursor-pointer sm:hidden">
      <span
        class="bar block h-1 w-6 bg-dark-black mx-auto my-1 transition-all duration-300 ease-in-out"
      ></span>
      <span
        class="bar block h-1 w-6 bg-dark-black mx-auto my-1 transition-all duration-300 ease-in-out"
      ></span>
      <span
        class="bar block h-1 w-6 bg-dark-black mx-auto my-1 transition-all duration-300 ease-in-out"
      ></span>
    </div>
  </nav>
</header>