Lamuni/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf.urls.i18n import i18n_patterns

urlpatterns = i18n_patterns(
    path('admin/', admin.site.urls),
    path("accounts/", include("Users.urls")),
    path("", include("Users.urls")),
    path("", include("Wallet.urls")),
    path("", include("Loans.urls")),
    path("accounts/", include("Users.urls")),
    path("fsp/", include("Loans.urls")),
    path('', include("Lessons.urls")),
    path('accounts/', include('django.contrib.auth.urls')),
    path('i18n/', include('django.conf.urls.i18n')),
    path('ckeditor/', include('ckeditor_uploader.urls')),
    # path('rosetta/', include('rosetta.urls')),
    prefix_default_language=True,
)

Loans/urls.py
from django.urls import path
from .views import create_loan, loan_details, dashboard, loans_list, fsp_profile, \
    loan_beneficiaries, add_record, add_sales_record, fs, fr, user_loan_details, \
    list_loans, apply_loan, users_credentials, grant_loan, deny_loan, generate_income_statement, \
    request_financial_statements, verify_transfer, beneficiary_data

app_name = 'loans'

urlpatterns = [
    path('add/record/', add_record, name='add-record'),
    path('fs/', fs),
    path('fr/<int:pk>/', fr),
    path('add/sales/record/', add_sales_record, name='add-sales-record'),
    path('pdf/', generate_income_statement),
    # path('balance-sheet/', GenerateBalanceSheet.as_view()),
    path('create-loan/', create_loan, name="create_loan"),
    path('loan-details/<int:pk>/', loan_details, name="loan_details"),
    path('user-loan-details/<int:pk>/', user_loan_details, name="user-loan-details"),
    path('dashboard/', dashboard, name="dashboard"),
    path('loans/', loans_list, name='loans_list'),
    path('fsp/profile/', fsp_profile, name='profile'),
    path('loans/<int:pk>/beneficiaries/', loan_beneficiaries, name='beneficiaries'),
    path('loans/<int:loan_pk>/beneficiaries/<int:beneficiary_pk>', beneficiary_data, name='beneficiary_data'),
    path('list-loans', list_loans, name="list_loans"),
    path('apply-loan/<int:id>/', apply_loan, name="apply_loan"),
    path('users-credential/<int:loan_id>/<slug:username>/', users_credentials, name="users_loan_requirements"),
    path('grant-loan/<int:loan_id>/<slug:username>/', grant_loan, name="approve_loan"),
    path('deny-loan/<int:loan_id>/<slug:username>/', deny_loan, name="deny_loan"),
    path('request-financial-statement/', request_financial_statements, name="request-statement"),
    path('transfer/verify', verify_transfer, name="verify_transfer"),
    # path("recommended-loans/", recommended_loans, name="recommended_loans")
]

Users/urls.py
from .views import (chating, index, register,verify_code, send_reset_code, reset_verify,
    reset_password, education,lesson_detail, lesson_done,  user_profile, conversation, financial_statement,
    update_user_profile,  verification)

from django.contrib.auth import views as auth_views
from django.urls import path

app_name = "users"

urlpatterns = [
    path("", index, name="index"),
    path("signup/", register, name="signup"),
    path('logout/', auth_views.LogoutView.as_view(template_name='registration/logout.html')),
    path('verify/<slug:username>/', verify_code, name="verify"),  # ← new
    path('send_reset/', send_reset_code, name="reset_code"),
    path('reset_verify/<slug:username>/', reset_verify, name="reset_verify"),
    path('password_reset/<slug:username>/<int:code>/', reset_password, name="reset_password"),
    path('profile/', user_profile, name="profile"),
    path('profile/update', update_user_profile, name="update_profile"),
    path("bot/", chating, name="bot"),
    path("conversation/", conversation, name="conversation"),
    path("financial-statement/", financial_statement, name="financial-statement"), 
    path('verify/', verification, name="verify")
]

Wallet/urls.py
from django.urls import path
from .views import view_wallet, recharge, withdraw, transfer

app_name = 'wallets'

urlpatterns = [
    path('wallet/', view_wallet, name='index'),
    path('wallet/recharge/', recharge, name='recharge'),
    path('wallet/withdraw/', withdraw, name='withdraw'),
    path('wallet/transfer/', transfer, name='transfer')
]

Loans/models.py
from importlib.metadata import requires
from pyexpat import model
from string import digits
from django.utils import timezone
from django.db import models
from django.contrib.auth import get_user_model
from django.urls import reverse
from multiselectfield import MultiSelectField
from datetime import datetime, timedelta

from django.conf import settings
from django.utils.timezone import make_aware
from django.shortcuts import get_object_or_404

from Users.models import Sector

# naive_datetime = datetime.now()
# naive_datetime.tzinfo
#
# settings.TIME_ZONE  # 'UTC'
# aware_datetime = make_aware(naive_datetime)
# aware_datetime.tzinfo  # <UTC>
#
# print(aware_datetime.tzinfo)

# Create your models here.
REQUIREMENTS = (('address', 'address'),
                ('bvn', 'bvn'), ('nin', 'nin'), ('business_certificate', 'business_certificate'),
                ('financial_record', 'financial_record'), ('time_in_business', 'time_in_business'),
                ('number_of_employee', 'number_of_employee'))
BUSINESS_SIZE = (('MICRO', 'MICRO'), ('SMALL', 'SMALL'), ('MEDIUM', 'MEDIUM'))


class FSP(models.Model):
    user = models.ForeignKey(get_user_model(), on_delete=models.DO_NOTHING, related_name='fsp_user')


# class FSP(models.Model):
#     user = models.ForeignKey(get_user_model(), on_delete=models.DO_NOTHING)


class Beneficiaries(models.Model):
    print("beneficairies model")
    user = models.ForeignKey(settings.AUTH_USER_MODEL, on_delete=models.DO_NOTHING, related_name="beneficiary")
    time_applied = models.DateTimeField(auto_now=True)
    time_payed = models.DateTimeField(blank=True, null=True)
    is_payed = models.BooleanField(default=False)
    time_to_pay = models.DateTimeField(blank=True, null=True)  # oficailly the time the loan suppose to be paid
    number_of_employee = models.PositiveIntegerField()
    is_given = models.BooleanField(default=False)
    is_denied = models.BooleanField(default=False)

    def __str__(self) -> str:
        return str(self.user.username)

    @property
    def is_recommended(self, loan_id):
        # TODO: check if the applicants credit score is greater than 50%
        loan = get_object_or_404(Loan, id=loan_id)
        all_beneficiaries = self.objects.filter(user=self.user, is_given=True, is_payed=False)
        if all_beneficiaries.exists():
            return (False, 0)
        if self.user.sector in loan.sectors.all() and self.user.size in loan.size:
            return (True, 10)
        elif self.user.size in loan.size:
            return (True, 7)
        elif self.user.sector in loan.sectors.all():
            return (True, 5)
        # call fake recommend api


class Requirement(models.Model):
    requirement = models.CharField(choices=REQUIREMENTS, max_length=50)

    def __str__(self) -> str:
        return str(self.requirement)


# for choice in REQUIREMENTS:
#     requirements = Requirement.objects.filter(requiremenent=choice[0])
#     if not requirements.exists():
#         Requirement.objects.create(requiremenent=choice[0])


class Loan(models.Model):
    fsp = models.ForeignKey(get_user_model(), on_delete=models.DO_NOTHING, related_name="fsp")
    description = models.TextField()
    date_created = models.DateTimeField(auto_now_add=True)
    program_title = models.CharField(max_length=200)
    size = MultiSelectField(choices=BUSINESS_SIZE, max_choices=3, max_length=100)
    sectors = models.ManyToManyField(Sector)
    amount = models.PositiveIntegerField()
    beneficiaries = models.ManyToManyField(Beneficiaries)
    is_active = models.BooleanField(default=True)
    paying_days = models.PositiveIntegerField()
    grace_period = models.PositiveIntegerField()
    collateral = models.CharField(max_length=200, blank=True, null=True)
    requirements = models.ManyToManyField(Requirement)
    intrest = models.PositiveIntegerField()

    def number_of_approved(self):
        beneficiaries = self.beneficiaries.all()
        count = 0
        for beneficiary in beneficiaries:
            if beneficiary.is_given:
                count += 1
        return count

    def get_sector_data(self):
        pass
        # beneficiaries = self.beneficiaries.all()
        # data = {}
        # for beneficiary in beneficiaries:
        #     sector = beneficiary.user.sector.all()
        #     print("sectors", sector)
        #     it_exist = data.get(sector.name, 0)
        #     if it_exist == 0:
        #         data[sector.name] = 1
        #     else:
        #         data[sector.name] += 1
        # return data

    # number_of_approved = loan.beneficiaries.filter(is_given=True).count()

    def number_of_yet_paid(self):
        beneficiaries = self.beneficiaries.all()
        count = 0
        for beneficiary in beneficiaries:
            if not beneficiary.is_payed:
                count += 1
        return count

    def number_of_paid(self):
        beneficiaries = self.beneficiaries.all()
        count = 0
        for beneficiary in beneficiaries:
            if beneficiary.is_payed:
                count += 1
        return count

    def grant_loan(self, user):
        # TODO: send notif or message to the user that loan granted
        application = self.beneficiaries.filter(user=user)
        print(application[0].is_given)
        if application.exists():
            the_id = application[0].id
            application = get_object_or_404(Beneficiaries, id=the_id)
            application.is_given = True
            application.is_denied = False
            application.time_to_pay = datetime.today() + timedelta(days=self.paying_days)
            application.save()
            return True
        return False

    def deny_loan(self, user):
        # TODO: deny loan tomorow test
        application = self.beneficiaries.filter(user=user)
        if application.exists():
            the_id = application[0].id
            application = get_object_or_404(Beneficiaries, id=the_id)
            # apply is_denied to be true
            application.is_denied = True
            application.is_given = False
            application.save()
            return True
            # TODO: send the user a sorry message that this isnt the right program for him
        return False

    def grant_recommended(self):
        # TODO: this will grant all recommended and deny all unrecommended
        for beneficiary in self.beneficiaries.all():
            if beneficiary.is_recommended(self.id)[0]:
                self.grant_loan(beneficiary.user)
            else:
                self.deny_loan(beneficiary.user)
        return None

    def get_absolute_url(self):
        return reverse('loans:user-loan-details', args=[self.pk])


RECORD_CATEGORY = (('Purchase', 'Purchase'),
                   ('Expenses', 'Expenses'),
                   ('Tax', 'Tax'),
                   ('Income', 'Income'))


class Record(models.Model):
    amount = models.DecimalField(max_digits=12, decimal_places=2, default=0)
    date = models.DateTimeField(auto_now=True)
    category = models.CharField(max_length=45, choices=RECORD_CATEGORY, default='', verbose_name='Category')
    description = models.CharField(max_length=40)


class SalesRecord(models.Model):
    item_name = models.CharField(max_length=200, blank=False, null=True)
    quantity = models.PositiveIntegerField(default=1)
    cost_price_per_item = models.DecimalField(max_digits=12, decimal_places=2, default=0)
    selling_price_per_item = models.DecimalField(max_digits=12, decimal_places=2, default=0)
    date = models.DateTimeField(auto_now=True)

    def get_profit(self):
        total_costs = self.quantity * self.cost_price_per_item
        total_sales = self.quantity * self.selling_price_per_item

        print('total_sales : ' + str(total_sales))
        print('self.quantity : ' + str(self.quantity))
        print('self.cost_price_per_item : ' + str(self.cost_price_per_item))
        print('self.selling_price_per_item : ' + str(self.selling_price_per_item))
        print('total_costs : ' + str(total_costs))

        return total_sales - total_costs

    @property
    def get_total_sales(self):
        total_sales = self.quantity * self.selling_price_per_item

        return total_sales

    @property
    def get_total_cost(self):
        total = self.quantity * self.cost_price_per_item

        print('get_total_cost : ' + str(total))
        return total


class FinancialRecord(models.Model):
    user = models.ForeignKey(get_user_model(), on_delete=models.DO_NOTHING)
    profit = models.DecimalField(max_digits=12, decimal_places=2, verbose_name="Profit", default=0)
    net_profit = models.DecimalField(max_digits=12, decimal_places=2, default=0)
    revenue = models.DecimalField(max_digits=12, decimal_places=2, default=0)
    records = models.ManyToManyField(Record, blank=True)
    sales_records = models.ManyToManyField(SalesRecord, blank=True)

    def get_ideal_profit(self):

        print(self)

        profit = 0

        start_date = datetime.today()
        end_date = start_date - timedelta(days=30)

        print('end date : ' + str(end_date))
        print('start date : ' + str(start_date))

        all_sales_records = self.sales_records.all()

        # print(all_sales_records)
        all_sales_records.filter(date__gte=end_date).filter(date__lte=start_date)

        for sales_record in all_sales_records.filter(date__gte=end_date).filter(date__lte=start_date):
            profit += sales_record.get_profit()
            print('get_ideal_profit : ' + str(profit))

        return profit

    @property
    def get_total_expenses(self):

        total_expenses = 0
        start_date = datetime.today()
        end_date = start_date - timedelta(days=30)

        print('end date : ' + str(end_date))
        print('start date : ' + str(start_date))

        all_records = self.records.all()

        for record in all_records.filter(date__gte=end_date).filter(date__lte=start_date).exclude(category="Expenses"):

Users/models.py
from pyexpat import model
from django.db import models
from django.contrib.auth.models import AbstractUser
from phonenumber_field.modelfields import PhoneNumberField
from .validators import validate_phone_number


class Sector(models.Model):
    name = models.CharField(max_length=200)

    def __str__(self) -> str:
        return str(self.name)


# Create your models here.
TIME_IN_BUSINESS_CHOICES = (('Less than 1 year', 'Less than 1 year'),
                            ('2 years', '2 years'),
                            ('3 years', '3 years'),
                            ('4 years', '4 years'),
                            ('5 years', '5 years'),
                            ('Above 5 years', 'Above 5 years'),)
                            
BUSINESS_SIZE = (('MICRO', 'MICRO'), ('SMALL', 'SMALL'), ('MEDIUM', 'MEDIUM'),)

class User(AbstractUser):
    middle_name = models.CharField(max_length=100, blank=True, )
    phone = models.CharField(max_length=20, blank=False, unique=True, null=True)
    image = models.ImageField(default='default.png', upload_to='profile_photo/%Y/%m/%d/')
    is_verified = models.BooleanField(default=False)
    is_number_verified = models.BooleanField(default=False)
    reset_code = models.CharField(max_length=8, help_text='Enter code')
    is_kyc_verified = models.BooleanField(default=False)
    date_of_birth = models.DateTimeField(blank=True, null=True)
    address = models.TextField(max_length=200, blank=True, null=True)
    state = models.CharField(max_length=100, blank=True, null=True)
    occupation = models.CharField(max_length=100, blank=True, null=True)
    bvn = models.PositiveIntegerField(blank=False, null=True)
    nin = models.PositiveIntegerField(blank=False, null=True)
    business_certificate = models.FileField(upload_to='business_certificate/%Y/%m/', null=True, blank=True)
    financial_record = models.FileField(upload_to='financial_record/%Y/%m/', null=True, blank=True)
    balance_sheet = models.FileField(upload_to='financial_record/%Y/%m/', null=True, blank=True)
    time_in_business = models.CharField(max_length=30, choices=TIME_IN_BUSINESS_CHOICES, blank=True, null=True)
    sector = models.ForeignKey(Sector, on_delete=models.DO_NOTHING, blank=True, null=True)
    size = models.CharField(choices=BUSINESS_SIZE, max_length=20)
    number_of_employee = models.PositiveIntegerField(blank=True, null=True)
    
    class Meta:
        permissions = [('can_create_loans', 'Can Create Loans')]

 
    def validate_bvn(request):
        """this will be used to validate uses bvn"""
        pass

templates/user/add_record.html
{% extends 'base.html' %}

{% block content %}
       <section class="container mx-auto">
        <div class="flex flex-col md:flex-row sm:space-x-6 my-5 sm:my-10 px-8 text-dark-black  max-w-[1280px]">
                 <!-- Profile section -->
                 <div class="flex flex-col mt-10 sm:mt-0 w-full md:w-3/5 mx-auto">
                       <a href="{% url 'users:profile' %}"> <button class="py-2 px-8 bg-white border my-4 md:my-6 border-gray-200 text-green-600 rounded hover:bg-white active:bg-gray-200 disabled:opacity-50">Back</button></a>
                    <!-- profile heading -->
                    <div class="shadow-md shadow-light-gray bg-white rounded-b-lg border-t-8 border-dark-green  px-4 sm:px-8">
                        <form method="post">
                            <div class="mt-8 grid grid-cols-1 gap-4">
                                    {% csrf_token %}
  <p>
    <label for="id_amount" class="text-sm text-gray-700 block mb-1 font-medium">Amount:</label>
     {{ form.amount }}

 {{ form.amount.errors }}
  </p>


  <p>
    <label for="id_category" class="text-sm text-gray-700 block mb-1 font-medium">Middle name:</label>
    {{ form.category }}

 {{ form.category.errors }}
  </p>



                            <div class="flex flex-col space-y-4 sm:flex-row sm:space-y-0 sm:space-x-4 w-full my-5 justify-end">
                <!-- Secondary -->

                                 <button type="submit" class="py-2 px-4 bg-green-500 text-white rounded hover:bg-green-600 active:bg-blue-700 disabled:opacity-50">Add Record</button>
              </div>
                                </div>

                        </form>
                    </div>


        </div>
       </section>
{% endblock %}

templates/user/add_sales_record.html
{% extends 'base.html' %}

{% block content %}
       <section class="container mx-auto">
        <div class="flex flex-col md:flex-row sm:space-x-6 my-5 sm:my-10 px-8 text-dark-black  max-w-[1280px]">
                 <!-- Profile section -->
                 <div class="flex flex-col  mt-10 sm:mt-0 w-full md:w-3/5 mx-auto">
                     <a href="{% url 'users:profile' %}"> <button class="py-2 px-8 bg-white border my-4 md:my-6 border-gray-200 text-green-600 rounded hover:bg-white active:bg-gray-200 disabled:opacity-50">Back</button></a>
                    <!-- profile heading -->
                    <div class="shadow-md shadow-light-gray bg-white rounded-b-lg border-t-8 border-dark-green  px-4 sm:px-8">
                        <form method="post">
                            <div class="mt-8 grid grid-cols-1 gap-4">
                                    {% csrf_token %}
  <p>
    <label for="id_item_name" class="text-sm text-gray-700 block mb-1 font-medium">Item Name:</label>
     {{ form.item_name }}

 {{ form.item_name.errors }}
  </p>


  <p>
    <label for="id_quantity" class="text-sm text-gray-700 block mb-1 font-medium">Quantity:</label>
    {{ form.quantity }}

 {{ form.quantity.errors }}
  </p>


  <p>
    <label for="id_cost_price_per_item" class="text-sm text-gray-700 block mb-1 font-medium">Cost Price Per Item:</label>
    {{ form.cost_price_per_item }}
 {{ form.cost_price_per_item.errors }}

  </p>


  <p>
    <label for="id_selling_price_per_item" class="text-sm text-gray-700 block mb-1 font-medium">Selling Price Per Item:</label>
  {{ form.selling_price_per_item }}

 {{ form.selling_price_per_item.errors }}
  </p>
              <div class="flex flex-col-reverse space-y-4 sm:flex-row sm:space-y-0 sm:space-x-4 w-full my-5 justify-end">
                <!-- Secondary -->

                                 <button type="submit" class="py-2 px-4 bg-green-500 text-white rounded hover:bg-green-600 active:bg-blue-700 disabled:opacity-50">Add Sales Record</button>
              </div>
                                </div>

                        </form>
                    </div>


        </div>
       </section>
{% endblock %}

templates/user/edit_profile.html
{% extends 'base.html' %}

{% block content %}
       <section class="container mx-auto">
        <div class="flex flex-col md:flex-row sm:space-x-6 my-5 sm:my-10 px-8 text-dark-black  max-w-[1280px]">
                 <!-- Profile section -->
                 <div class="flex flex-col  mt-10 sm:mt-0 w-full md:w-3/5 mx-auto">
                       <a href="{% url 'users:profile' %}"> <button class="py-2 px-8 bg-white border my-4 md:my-6 border-gray-200 text-green-600 rounded hover:bg-white active:bg-gray-200 disabled:opacity-50">Back</button></a>
                    <!-- profile heading -->
                    <div class="shadow-md shadow-light-gray bg-white rounded-b-lg border-t-8 border-dark-green  px-4 sm:px-8">
                        <form method="post">
                            <div class="mt-8 grid grid-cols-1 gap-4">
                                    {% csrf_token %}
                                    <p>
    <label for="id_image" class="text-sm text-gray-700 block mb-1 font-medium">Image:</label>
     {{ form.image }}

    {{ form.image.errors }}

  </p>


  <p>
    <label for="id_first_name" class="text-sm text-gray-700 block mb-1 font-medium">First name:</label>
     {{ form.first_name }}

 {{ form.first_name.errors }}
  </p>


  <p>
    <label for="id_middle_name" class="text-sm text-gray-700 block mb-1 font-medium">Middle name:</label>
    {{ form.middle_name }}

 {{ form.middle_name.errors }}
  </p>


  <p>
    <label for="id_last_name" class="text-sm text-gray-700 block mb-1 font-medium">Last name:</label>
    {{ form.last_name }}
 {{ form.last_name.errors }}

  </p>


  <p>
    <label for="id_email" class="text-sm text-gray-700 block mb-1 font-medium">Email address:</label>
  {{ form.email }}

 {{ form.email.errors }}
  </p>


   <p>
    <label for="id_date_of_birth_month" class="text-sm text-gray-700 block mb-1 font-medium">Date of birth:</label>
   {{ form.date_of_birth}}
       {{ form.date_of_birth.errors }}


  </p>



  <p>
    <label for="id_phone" class="text-sm text-gray-700 block mb-1 font-medium">Phone:</label>

 {{ form.phone }}
       {{ form.phone.errors }}
  </p>


  <p>
    <label for="id_state" class="text-sm text-gray-700 block mb-1 font-medium">State:</label>
       {{ form.state }}

 {{ form.state.errors }}

  </p>


  <p>
    <label for="id_occupation" class="text-sm text-gray-700 block mb-1 font-medium">Occupation:</label>
   {{ form.occupation }}


 {{ form.occupation.errors }}

  </p>

                            <div class="flex flex-col space-y-4 sm:flex-row sm:space-y-0 sm:space-x-4 w-full my-5 justify-end">
                <!-- Secondary -->

                                 <button type="submit" class="py-2 px-4 bg-green-500 text-white rounded hover:bg-green-600 active:bg-blue-700 disabled:opacity-50">Update Profile</button>
              </div>
                                </div>

                        </form>
                    </div>


        </div>
       </section>
{% endblock %}

templates/user/user_loan_details.html
{% extends 'base.html' %}
{% block title %} Loans {% endblock %}

{% block content %}


<section class="mx-auto max-w-3xl  " >
    <div class="my-5 sm:my-10 mx-4">
      <a href="{% url 'loans:dashboard' %}"> <button class="py-2 px-8 bg-white border my-4 md:my-6 border-gray-200 text-green-600 rounded hover:bg-gray-100 active:bg-gray-200 disabled:opacity-50">Back</button></a>




    <div class="bg-white shadow-md rounded-lg shadow-light-gray flex flex-row items-center justify-between">
    <div class="flex flex-row items-center mx-4">
      <div class="flex flex-col justify-between">
                <h3 class="text-base sm:text-lg">{{ loan.fsp }}'s Loan</h3>
                 <span class="mt-2">
                     {% if loan.is_active %}
                         <span class="bg-green-500 py-1 px-2 rounded text-white text-sm">Status: Active</span>
                     {% else %}
                         <span class="bg-red-500 py-1 px-2 rounded text-white text-sm">Status: Deactivated</span>
                     {% endif %}
                 </span>
            </div></div>

        <div class="flex items-center p-4 flex-initial">

           <a href="{% url 'loans:apply_loan' loan.id %}"> <button class=" px-4 text-xs sm:text-base sm:px-6 py-2 rounded-lg bg-green-100 text-green-700 hover:bg-green-300 transition-all duration-150"> Apply Now</button></a>
        </div>
    </div>
    <div class="bg-white shadow-md shadow-light-gray rounded-lg flex flex-col my-10  p-4 sm:p-8">

        <div class=" flex flex-col bg-white shadow-sm shadow-light-gray p-4 sm:p-6 relative">
          {% with loan.fsp as user %}
         <img class="absolute top-0 -mt-6  rounded-lg bg-blend-lighten shadow-lg" width="50px"  src="{{ user.image.url }}" alt="">
            {% endwith %}
            <p class="text-sm text-dark-gray mt-4">{{ loan.date_created | date }}</p>
            <h3 class=" flex-none text-lg md:text-xl bold tracking-wide">{{ loan.program_title }}</h3>
            <p class="text-dark-gray ">Amount: {{ loan.amount }}</p>
            <p class="text-dark-green mt-4 sm:mt-6">Sector: {% for sector in loan.sectors.all %}{{  sector.name }}{% endfor %}, Size:{{ loan.size }}</p>

        </div>
    <div class="my-5">
        <h1 class="text-lg font-bold tracking-wider">Description</h1>
        <p class="text-sm sm:text-base tracking-wide sm:tracking-wider text-justify">
           {{ loan.description }}
        </p>
    </div>

    <div class="my-5">
        <h1 class="text-lg font-bold tracking-wider">Requirements</h1>
        <p class="text-sm sm:text-base tracking-wide sm:tracking-wider text-justify">
            {% for requirement in loan.requirements.all  %}
                <p>{{ requirement }}</p>

            {% endfor %}
        </p>
    </div>
    <div class="flex items center justify-end my-5">
        <a href="{% url 'loans:apply_loan' loan.id %}"> <button class=" px-4 text-xs sm:text-base sm:px-6 py-2 rounded-lg bg-green-100 text-green-700 hover:bg-green-300 transition-all duration-150"> Apply Now</button></a>
    </div>
</div>

</section>







{% endblock %}

templates/user/users_credentials.html
{% extends 'base.html' %}

{% block content %} 
{{ credentials }}
{% for credential in credentials %}

{{ crendential }}
p
{% endfor %}
{% endblock %}

templates/user/verification_success.html
{% extends 'base.html' %} {% block content %}
    <div class="max-w-3xl mx-auto min-h-[400px]">
    <div class="mx-4 sm:mx-8">
         <a href="{% url 'loans:dashboard' %}"> <button class="  py-2 px-8 bg-white border my-4 md:my-6 border-gray-200 text-green-600 rounded hover:bg-white active:bg-gray-200 disabled:opacity-50">Back</button></a>
    <div class=" p-8 sm:p-16 shadow-md shadow-light-gray text center rounded-lg text-dark-orange sm:text-3xl">  {{ message }}</div>



    </div>

    </div>

{% endblock %}